pipeline(bosh|precompile): fix stemcell version consistency
we use stemcell version directly from 'root-deployment.yml' instead of injecting it through pipeline variables

diff --git a/concourse/tasks/download_stemcell/task.yml b/concourse/tasks/download_stemcell/task.yml
--- a/concourse/tasks/download_stemcell/task.yml
+++ b/concourse/tasks/download_stemcell/task.yml
@@ -18,6 +18,8 @@ image_resource:
   source:
     repository: ((docker-registry-url))governmentpaas/awscli
     tag: 19d32c252e328a762f75417fcee7cab6dbac9e97
+inputs:
+  - name: templates-resource
 outputs:
   - name: logs-dir
   - name: stemcell
@@ -26,6 +28,27 @@ run:
   args:
     - -ec
     - |
+      cat >script.py <<EOF
+      import yaml
+      import os
+      version_file_env=os.getenv('VERSIONS_FILE')
+      versions_file=open(version_file_env)
+      loaded_file=yaml.load(versions_file, Loader=yaml.FullLoader)
+      version=loaded_file.get('stemcell',{}).get('version')
+      if version:
+        print(version)
+      EOF
+
+      echo "Extracting stemcell version from $VERSIONS_FILE"
+      #STEMCELL_VERSION=$(python3 -c "import yaml;import os;version_file_env=os.getenv('VERSIONS_FILE');versions_file=open(version_file_env);loaded_file=yaml.load(versions_file, Loader=yaml.FullLoader);v=loaded_file.get('stemcell').get('version');print(v)")
+      STEMCELL_VERSION=$(python3 script.py)
+      if [ -z "$STEMCELL_VERSION" ]; then
+        echo "ERROR: failed to extract version from $VERSIONS_FILE"
+        exit 1
+      else
+        echo "Stemcell version found: $STEMCELL_VERSION"
+      fi
+
 
       STEMCELL_URL="${STEMCELL_BASE_LOCATION}/${STEMCELL_PREFIX}${STEMCELL_MAIN_NAME}?v=$STEMCELL_VERSION"
       TGZ_NAME="${STEMCELL_PREFIX}stemcell-$STEMCELL_VERSION-$STEMCELL_MAIN_NAME.tgz"
@@ -35,7 +58,7 @@ run:
       echo "Downloading ${TGZ_NAME%.tgz} from <$STEMCELL_URL>"
       curl -SsL "$STEMCELL_URL" > stemcell/${TGZ_NAME}
 params:
-  STEMCELL_VERSION:
+  VERSIONS_FILE:
   STEMCELL_PREFIX:
   STEMCELL_MAIN_NAME:
   STEMCELL_BASE_LOCATION: https://bosh.io/d/stemcells/
