feature(support-release-repackaging-fallback): direct download from bosh.io or github for releases on repackaging errors
We add an new task to handle fallback called `repackage_release_fallback`. This lower repackage task complexity and reduces coupling between repackaging and fallback mechanism.
We also integrate repackage_boshreleases_fallback task into bosh deployment and precompile pipelines.

We try to download from bosh.io first, when it fails, we try to download from github.
There are some restrictions to be able to download tgz from github, the download url must match: https://github.com/<repository>/releases/download/<tag_prefix><version>/<boshrelease_name>-<version>.tgz
<__value__> are defined in 'root-deployment.yml'

we also fix git_hard_reset_wip and git_rebase_status tests, as it seems coping files to setup tests generates some inconsistencies while running in concourse

diff --git a/concourse/pipelines/template/bosh-precompile-pipeline.yml.erb b/concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
--- a/concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
+++ b/concourse/pipelines/template/bosh-precompile-pipeline.yml.erb
@@ -244,9 +244,12 @@ jobs:
           BOSH_CA_CERT: secrets/<%= PipelineGenerator::BOSH_CERT_LOCATIONS[root_deployment_name] %>
           ROOT_DEPLOYMENT_NAME: <%= root_deployment_name %>
 
+      - task: repackage-releases-fallback
+        file:  cf-ops-automation/concourse/tasks/repackage_boshreleases_fallback/task.yml
+
         <% if offline_boshreleases_enabled %>
       - task: upload-repackaged-releases
-        input_mapping: { local-files-dir: repackaged-releases, templates-resource: paas-templates-<%= root_deployment_name %>-limited }
+        input_mapping: { local-files-dir: repackaged-releases-fallback, templates-resource: paas-templates-<%= root_deployment_name %>-limited }
         file:  cf-ops-automation/concourse/tasks/s3_boshreleases_upload/task.yml
         params:
           BUCKET: ((s3-br-bucket))
@@ -258,7 +261,7 @@ jobs:
         <% end %>
       - task: upload-to-director
         attempts: 2
-        input_mapping: { config-resource: secrets-full-writer }
+        input_mapping: { releases-to-upload: repackaged-releases-fallback, config-resource: secrets-full-writer }
         file:  cf-ops-automation/concourse/tasks/bosh_upload_releases/task.yml
         params:
           BOSH_CLIENT: ((bosh-username))
@@ -274,19 +277,34 @@ jobs:
               repository: ((docker-registry-url))governmentpaas/curl-ssl
               tag: 2857fdbaea59594c06cf9c6e32027091b67d4767
           inputs:
-            - name: repackaged-releases
+            - name: repackaged-releases-fallback
           run:
             path: sh
             args:
               - -ec
               - |
-                cd repackaged-releases
-                if [ -e errors.yml ]; then
-                  cat errors.yml
-                  exit 1
-                else
-                  echo "No errors detected"
+                cd repackaged-releases-fallback
+                if [ -e fallback-fixes.yml ]; then
+                echo "=========================================================="
+                  echo "Dump fallback-fixes"
+                  cat fallback-fixes.yml
                 fi
+                echo "=========================================================="
+                  if [ -e fallback-errors.yml ]; then
+                  echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\"
+                  echo "Dump fallback-errors"
+                    cat fallback-errors.yml
+                  echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\"
+                    exit 1
+                  elif [ -e errors.yml ]; then
+                  echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\"
+                  echo "Dump errors"
+                    cat errors.yml
+                  echo "/!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\ /!\"
+                    exit 1
+                  else
+                    echo "No errors detected"
+                  fi
   - name: push-stemcell
     <% jobs['Utils'] << 'push-stemcell' %>
     on_failure:
